### ISSUE TITLE
Mac compatible? Can this be used with OSX Mojave since it's Linux based? Specs: XPS 13 Hackintosh 9360 i7 8550u

### ISSUE THREAD

**Issue by 13xps** [erpalma/lenovo-throttling-fix#76] opened 2018-11-28 11:59 UTC
Has anyone used this with OSX? Particularity hackintosh? My setup is XPS 13 Hackintosh 9360 i7 8550u on Mojave

**Comment by erpalma** [comment] 2018-11-28 12:40
Duplicate of #60

**Closed by erpalma** 2018-11-28 12:40 UTC
